services:
    api:
        build: ./backend
        ports:
            - "4000:4000"
        env_file:
            - ./backend/.env
    frontend:
        build: ./front-end
        ports:
            - "3000:3000"
        depends_on:
            - api
