name: Node.js CI

on: [push]

jobs:

  backend:
    name: Backend Tests (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22, 24]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies on backend
        run: |
          cd backend
          npm install

      - name: Run backend tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_URL: ${{ secrets.DB_URL }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: |
          cd backend
          npm run test

  frontend:
    name: Frontend Build (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22, 24]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies on frontend
        run: |
          cd front-end
          npm install

      - name: Build frontend
        run: |
          cd front-end
          npm run build
